apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "heal-map-client.fullname" . }}
  labels:
    {{- include "heal-map-client.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "heal-map-client.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "heal-map-client.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: heal-map-client
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 80
              name: http
