apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "heal-map-client.fullname" . }}
  labels:
    {{- include "heal-map-client.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "heal-map-client.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "heal-map-client.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: heal-map-client-helper-geojson-import
          image: "{{ .Values.helper.image.repository }}:{{ .Values.helper.image.tag }}"
          {{- with .Values.helper.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.helper.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: geojson-volume
              mountPath: /home/heal/aois
      containers:
        - name: heal-map-client
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: geojson-volume
              mountPath: /usr/share/nginx/html/static/aois
      volumes:
        - name: geojson-volume
          emptyDir: {}
