name:  Crowdin To GitHub

on:
  workflow_dispatch:
  schedule:
    - cron: '15 * * * *' # sync every hour

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync Crowdin to Github
        uses: crowdin/github-action@v1.19.0
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          localization_branch_name: i18n_crowdin
          create_pull_request: true
          push_sources: false
          pull_request_title: 'New Crowdin Translations'
          pull_request_body: 'New Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action)'
          pull_request_base_branch_name: 'main'
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
