name: HEAL

on:
  push:
    branches:
      - heal

jobs:
  deploy:
    environment: heal
    runs-on: [self-hosted, ors-map-client-heal]
    steps:
      - name: trigger branch name
        run: echo ${GITHUB_REF_NAME}
      - name: fetch repo state and prune remotes
        working-directory: ${{ secrets.work_dir }}
        run: git fetch --prune
      - name: checkout trigger branch
        working-directory: ${{ secrets.work_dir }}
        run: git checkout --progress --force ${GITHUB_REF_NAME}
      - name: hard reset to origin state
        working-directory: ${{ secrets.work_dir }}
        run: git reset --hard origin/${GITHUB_REF_NAME}
      - name: build docker rebuild and restart
        working-directory: ${{ secrets.work_dir }}
        run: docker compose up --build --force-recreate -d
