name: Test webapp
on:
  # Triggers the workflow on push for the main/master branch and on all pull requests.
  push:
    branches:
    - main
    - master
  pull_request:
    branches: [ "**" ]
jobs:
  Run-lint:
    strategy:
      fail-fast: false # Good to fail all fast if one of the matrix runs fails.
      matrix:
        node-version: [ 12 ]
        python-version: [ "3.10" ]
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install lint dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Install and run pre-commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files
  Run-tests:
    needs:
      - Run-lint
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up default config files
        run: cd src && cp config-examples/* config && for i in config/*-example.js; do mv -- "$i" "${i%-example.js}.js"; done
      - name: Run test target
        env:
          ORSKEY: ${{ secrets.ORSKEY }}
          BITLYLOGIN: ${{ secrets.BITLYLOGIN }}
          BITLYAPIKEY: ${{ secrets.BITLYAPIKEY }}
        uses: GIScience/github-action-webapp-front-end-test@v1.4
        with:
          target: 'test'
